# Generated by Django 5.0.3 on 2024-09-03 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('ежегодный оплачиваемый', 'Ежегодный оплачиваемый'), ('без сохранения заработной платы', 'Без сохранения заработной платы'), ('учебный', 'Учебный'), ('по родам, кормлению и уходу за ребенком', 'По родам, кормлению и уходу за ребенком'), ('командировка', 'Командировка')], max_length=100, verbose_name='Тип отпуска'),
        ),
        migrations.CreateModel(
            name='UserLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_days', models.IntegerField(default=30, verbose_name='Оставшиеся дни отпуска')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leave_balances', to='main.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
