# Generated by Django 5.0.3 on 2024-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_leavetype_name_userleavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('available_slots', models.IntegerField(default=3)),
            ],
        ),
    ]
