# Generated by Django 5.0.3 on 2024-09-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vacationslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationslot',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
