# Generated by Django 5.0.3 on 2024-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userprofile_position_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('under_consideration', 'Under Consideration'), ('proposed_change', 'Proposed Change')], default='under_consideration', max_length=20, verbose_name='Статус'),
        ),
    ]
